export const PROJECT_FORM = 'PROJECT_FORM';
export const GET_PROJECTS = 'GET_PROJECTS';
export const ADD_PROJECT = 'ADD_PROJECT';
export const CHECK_FORM = 'CHECK_FORM';
export const CURRENT_PROJECT = 'CURRENT_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
//TASKS
export const PROJECT_TASK = 'PROJECT_TASK';
export const ADD_TASK = 'ADD_TASK';
export const CHECK_TASKFORM = 'CHECK_TASKFORM';
