export const PROJECT_FORM = 'PROJECT_FORM';
export const GET_PROJECTS = 'GET_PROJECTS';
export const ADD_PROJECT = 'ADD_PROJECT';
export const CHECK_FORM = 'CHECK_FORM';
export const CURRENT_PROJECT = 'CURRENT_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const PROJECT_ERROR = 'PROJECT_ERROR';
//TASKS
export const PROJECT_TASK = 'PROJECT_TASK';
export const ADD_TASK = 'ADD_TASK';
export const CHECK_TASKFORM = 'CHECK_TASKFORM';
export const DELETE_TASK = 'DELETE_TASK';
export const CURRENT_TASK = 'CURRENT_TASK';
export const UPDATE_TASK = 'UPDATE_TASK';
export const CLEAN_TASK = 'CLEAN_TASK';
//ALERT
export const DISPLAY_ALERT = 'DISPLAY_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';
//AUTHENTICATION
export const REGISTRY_SUCCESS = 'REGISTRY_SUCCESS';
export const REGISTRY_ERROR = 'REGISTRY_ERROR';
export const GET_USER = 'GET_USER';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const SIGN_OFF = 'SIGN_OFF';
